### ISSUE TITLE
missing file?

### ISSUE THREAD

**Issue by findme8** [claroche-r/FastDiffusionEM#1]
Hey, I'm quite interested in this work. 

When I run the test code, there is error. Could you point me where I can find ''model_zoo/kernel_denoiser.pth''?

Thanks.

**Comment by claroche-r** [comment]
Hi,

Here are the weights of the kernel denoisers: https://drive.google.com/drive/folders/1pueQC9FI0ozoSUiu4u1MlJR52zYSnvKr?usp=share_link

The folder contains a kernel denoiser trained on 33x33 kernels and 64x64 kernels. In the paper experiments, we only used the 33x33 model (kernel_denoiser_33.th) so using the 64x64 model might necessitate some tuning.

I will point to the Google Drive link in the README, thanks for your interest.

Charles
