### ISSUE TITLE
Requirement for the dataset of motion blur kernels

### ISSUE THREAD

**Issue by Coderbai** [claroche-r/FastDiffusionEM#3]
Hi, I appreciate the nice job.

We want to train our own denoiser on this dataset mentioned in the paper, but we can not find it.

Do you have a plan to release the dataset?

**Comment by claroche-r** [comment]
Hi,

Here is the download link to the dataset we used: https://drive.google.com/file/d/1fDtSwItCCqob6ZJ_zvVfvQJ8U1q7dV7D/view?usp=share_link

As an alternative, you can use the motion blur generator used in DPS and Blind DPS which is available here: https://github.com/LeviBorodenko/motionblur

Depending on the data you want to test on, you might prefer to use one or the other. 

Best,
Charles
