### ISSUE TITLE
A question about kernel_denoiser_64.pth

### ISSUE THREAD

**Issue by Davinccci** [claroche-r/FastDiffusionEM#5]
Great work！ However, when I tested using the kernel_denoiser_64.pth model you provided, I found that the blur kernel generated after regularization is incorrect (as shown in the first image). This issue does not occur when using the kernel_denoiser_33.pth model (as shown in the second image). Can you explain why this might be happening？ Thank you!
![x_0990_ker_64](https://github.com/claroche-r/FastDiffusionEM/assets/52913501/9dabb56a-5971-4480-8eda-d5991cf921d1)
![x_0990_ker_33](https://github.com/claroche-r/FastDiffusionEM/assets/52913501/5ea1ae96-3bdd-4c0b-b6bc-872fb2be9b18)

**Comment by claroche-r** [comment]
Hi Davinccci,

You are right there is a problem with this denoiser. I am going to delete this version from the drive.
Once I investigate what's wrong with the model, I might upload another 64x64 model.

Sorry for the inconvenience.

Charles Laroche

**Comment by Davinccci** [comment]
Thank you for your reply, I look forward to your update!

**Comment by claroche-r** [comment]
It should be good by now, the new pre-trained model is in the drive.

I did not have the time to do extensive hyper-parameters tuning so you might want to re-tune the parameter controlling the strength of the regularization ($\lambda$) depending on your use case. 

Note that this parameter is different for the 64 model than for the 33 model: https://github.com/claroche-r/FastDiffusionEM/blob/7f161175b3b440378581c69df67a9bae0a30fe2a/guided_diffusion/gaussian_diffusion.py#L687-L692

Don't hesitate to tell me if you run into another bug.

**Comment by Davinccci** [comment]
Thank you for the update. The model now runs effectively. In fact, during runtime, I found a mismatch between the parameters of the 64 model and the predefined FdnCNN network. Upon comparing parameters, I discovered that the model's network should be the UNetRes model. After replacing it, the model runs smoothly.  

Also, when I use your code for the FFHQ 64*64 deblurring experiment, I find that some images are restored very well, while others fail to restore. Is this normal?

Thank you again for your prompt responses and updates.

**Comment by Sci-Epiphany** [comment]
Thank you very much for your help. Where can I find the appropriate 64x64 kernel denoising model weights?

**Comment by Sci-Epiphany** [comment]
> Thank you for the update. The model now runs effectively. In fact, during runtime, I found a mismatch between the parameters of the 64 model and the predefined FdnCNN network. Upon comparing parameters, I discovered that the model's network should be the UNetRes model. After replacing it, the model runs smoothly.
> 
> Also, when I use your code for the FFHQ 64*64 deblurring experiment, I find that some images are restored very well, while others fail to restore. Is this normal?
> 
> Thank you again for your prompt responses and updates.

I hope you don’t mind me asking a few questions—I’d really appreciate your guidance if you have the time. When I was working on motion deblurring using other regularization methods, I noticed some images yielded relatively good results,  while others fail to restore. I’m curious: have you already addressed this specific scenario, and if so, could you share a bit about how you approached it? Additionally, I was wondering if you still have a trained 64x64 denoising model available. Your help would mean a lot to me, and I’m truly grateful for any support you can offer.
